### ISSUE TITLE
BossBar#viewers always return an empty list

### ISSUE THREAD

**Issue by GoodestEnglish** [MockBukkit/MockBukkit#1002]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest version of MockBukkit?

- [X] I am using the latest version of MockBukkit.

### Minecraft Version

1.20

### Describe the bug

So if you try to use `BossBar#viewers` to loop the current viewers and remove viewers from the BossBar, it doesn't produce the excepted result.

### Reproducible Test

Just try to use this code to test, and you will be able to reproduce the unexcepted result.
```java
    @Test
    void test() {
        PlayerMock player = server.addPlayer();
        BossBar bossBar = BossBar.bossBar(Component.text("hello world"),1, BossBar.Color.RED, BossBar.Overlay.PROGRESS);

        bossBar.addViewer(player);

        assertTrue(player.getBossBars().contains(bossBar)); //Passed :D

        bossBar.viewers().forEach(viewer -> {
            if (viewer instanceof Player p) {
                bossBar.removeViewer(p);
            }
        });

        assertFalse(player.getBossBars().contains(bossBar)); //Failed :(
    }
```

**Comment by Thorinwasher** [comment]
I can reproduce this.

We need to register a service for this to work properly
