### ISSUE TITLE
Item Serialization

### ISSUE THREAD

**Issue by nicolube** [MockBukkit/MockBukkit#1013]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

Hello there,

I need some Item Serialization, I would also implement it.

Some rudimentary serialization well be enough for what I need, would it be fine if I add a MockSerializer in UnsafeValues?

Serializes ItemStack:
- Only ItemMeta
- Incompatible with CraftmagicNumbers (Craftbukkit UnsafeValues)
- Maype more metas as I go along

The goal is here to just add some basic serialization so that lager serializable structures can be tested.

**Comment by Thorinwasher** [comment]
Seems like it's unimplemented at the moment. Sure go ahead!
