### ISSUE TITLE
Adopt paper 1.21 ItemStack delegation

### ISSUE THREAD

**Issue by lynxplay** [MockBukkit/MockBukkit#1028]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

Paper 1.21 will have all [ItemStack](https://jd.papermc.io/paper/1.20.6/org/bukkit/inventory/ItemStack.html) methods simply call a delegate [ItemStack](https://jd.papermc.io/paper/1.20.6/org/bukkit/inventory/ItemStack.html) instance, which holds a CraftItemStack.

This enables ItemStack to have direct access to a server internal impl and is the first step to moving [ItemStack](https://jd.papermc.io/paper/1.20.6/org/bukkit/inventory/ItemStack.html) over to an interface.

As such, the constructor for [ItemStack](https://jd.papermc.io/paper/1.20.6/org/bukkit/inventory/ItemStack.html) 
will either make use of ItemType (and its respective implementation) or a new method `UnsafeValues#createEmptyStack`.

To properly support plugins creating ItemStacks, MockBukkit will need to mock [ItemType#createItemStack(int)](https://jd.papermc.io/paper/1.20.6/org/bukkit/inventory/ItemType.html#createItemStack(int)) and the previously mentioned `UnsafeValues#createEmptyStack`.

See: https://github.com/PaperMC/Paper/pull/10852.

**Comment by Thorinwasher** [comment]
@thelooter we merged the 1.21 update. This can be closed, right?

**Comment by thelooter** [comment]
I wouldn't close this yet until we have confirmed 100% compatibility with the nms Itemstack

**Comment by Thorinwasher** [comment]
I will try to create some proper tests that directly uses test data generated by MetaMiner (this might be a good idea to do in other areas as well). So gonna self assign myself this, and then confirm that the merged changes are valid.
