### ISSUE TITLE
Adventure's PlainTextComponentSerializer does not translate Minecraft Language Codes

### ISSUE THREAD

**Issue by willkroboth** [MockBukkit/MockBukkit#1040]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest version of MockBukkit?

- [X] I am using the latest version of MockBukkit.

### Minecraft Version

1.20

### Describe the bug

When running on a server, using [Minecraft Language Codes](https://gist.github.com/sppmacd/82af47c83b225d4ffd33bb0c27b0d932#:~:text=argument.range.empty) inside translatable Adventure Components is handled automatically. For example, if I have this plugin:

```java

public class BukkitTestPlugin extends JavaPlugin {
    @Override
    public void onEnable() {
        getLogger().info(getMessageString());
    }

    public Component getMessageComponent() {
        return Component.translatable("argument.range.empty");
    }

    public String getMessageString() {
        return PlainTextComponentSerializer.plainText().serialize(getMessageComponent());
    }
}
```

The following message appears in the console:

```log
[BukkitTestPlugin] Expected value or range of values
```

However, when running tests through MockBukkit, these components are serialized as their translation key, in this case `argument.range.empty`.

### Reproducible Test

```java
public class ComponentTest {
    @Test
    void test() {
        MockBukkit.mock();
        BukkitTestPlugin plugin = MockBukkit.load(BukkitTestPlugin.class);

        Assertions.assertEquals("Expected value or range of values", plugin.getMessageString());
        
        MockBukkit.unmock();
    }
}

ComponentTest.test:13 expected: <Expected value or range of values> but was: <argument.range.empty>
```

### Anything else?

I originally asked about this on the [Paper Discord](https://discord.com/channels/289587909051416579/555462289851940864/1259993507658076351). I thought it might be possible to register the translation keys myself into Adventure's [GlobalTranslator](https://docs.papermc.io/paper/dev/component-api/i18n#globaltranslator). The Paper team mentioned that the `en_us.json` file should be present in the server jar, so I tried loading translations like so:

```java
private void setupTranslations() {
	TranslationRegistry registry = TranslationRegistry.create(Key.key("minecraft:english"));

	Class<?> nmsClass;
	try {
		nmsClass = Class.forName("net.minecraft.server.Language");
	} catch (ClassNotFoundException e) {
		// In this case, the code stops here
		throw new IllegalStateException("Could not load translations!", e);
	}

	// I could never find this resource
	try (InputStream input = nmsClass.getResourceAsStream("/assets/minecraft/lang/en_us.json")) {
		if (input == null) throw new IllegalStateException("Could not load translations! InputStream was null.");
		JsonObject jsonObject = new Gson().fromJson(new InputStreamReader(input, StandardCharsets.UTF_8), JsonObject.class);

		for (Map.Entry<String, JsonElement> entry : jsonObject.entrySet()) {
			registry.register(entry.getKey(), Locale.US, new MessageFormat(entry.getValue().getAsString()));
		}
	} catch (IOException e) {
		throw new IllegalStateException("Could not load translations!", e);
	}

	GlobalTranslator.translator().addSource(registry);
}
```

However, I was never able to find the `en_us.json` file, and it seems plausible that this file is simply not included in the classpath when running with MockBukkit.

The Paper team also mentioned that 'PaperAdventure usually hooks into the default Minecraft translations' without using GlobalTranslator (https://discord.com/channels/289587909051416579/555462289851940864/1259995435964039198), so maybe that's a pathway MockBukkit can use. I suppose something about the PlainTextComponentSerializer provided by MockBukkit vs Paper is missing this part.

**Comment by Thorinwasher** [comment]
@willkroboth could you show me a minimal reproducible test for this. I made an implementation, but it would be good if it worked for you as well

**Comment by willkroboth** [comment]
I think [the test](https://github.com/MockBukkit/MockBukkit/pull/1077/files#diff-a74e7e4fa32abd7f307f54599b461e847807ef8f34a74593abcf03189ee84df6R17) you have in the PR makes sense, just making sure that `Component#translatable` can reference a default Minecraft key.

You could also test that these translatable messages can accept arguments. Something like this for example:

```java
TranslatableComponent translatableComponent = Component.translatable("argument.entity.selector.unknown", Component.text("@h"));
assertEquals("Unknown selector type '@h'", PlainTextComponentSerializer.plainText().serialize(translatableComponent));
```

I built your branch locally and tested it with my setup. Plain and translations with arguments seemed to work as expected :+1: .

**Comment by Thorinwasher** [comment]
> You could also test that these translatable messages can accept arguments. Something like this for example:

So that's how that works. Will definitely add a test for that
