### ISSUE TITLE
Hacktoberfest 2020 (Preptember)

### ISSUE THREAD

**Issue by TheBusyBiscuit** [MockBukkit/MockBukkit#106]
Hey (sorry for abusing the Issues section like this but it's the only way of contact I know for this project),

Are you familiar with Hacktoberfest? It's a yearly event that encourages developers to contribute to Open-Source projects via Pull Requests.
https://hacktoberfest.digitalocean.com/

Every public Pull Request on GitHub is counted for the event anyway, so you wouldn't have to set up anything explicitly.
But there are some things that are encouraged, such as writing a `CONTRIBUTING.md` file or creating Issues with the `Hacktoberfest` label, so participants will see that this project is worth contributing to.

Since this is a gigantic project with lots of implementation gaps to fill, I think it would be perfect to create some issues for missing features, label them and then see if someone finds it and creates a Pull Request.
It's really a win-win situation and encourages contributions.
I myself have participated last year and I will be participating this year too, I will very likely make one or more Pull Requests to this repository in the coming month anyway, so might as well do it during that event.

Anyway, before Hacktober comes Preptember in which maintainers are encouraged to prepare repositories for Open-Source contributions, such as creating the aforementioned issues.
What do you think? @seeseemelk 

*Note that I am not affiliated with the organization behind this event, I just really like Hacktoberfest and think it would be a great oppurtunity to encourage more people to contribute to this project.*

**Comment by seeseemelk** [comment]
I had never heard of Hacktoberfest before, but it definitely seems interesting and given the nature of MockBukkit, I think this project would indeed be a great candidate. I'll add a label for Hacktoberfest and make some issues, maybe even get started on a `CONTRIBUTING.md`.

**Comment by seeseemelk** [comment]
Big important question: what colour to use for the label? For now I used standard purple, but their website is using something more pink-y

**Comment by seeseemelk** [comment]
Ah, probably `#9C4668` according to [brand guidelines](https://www.figma.com/proto/oc9p0mS6A0cAOOhipLT9aV/DODX-959-Hacktoberfest-2020-Brand-Guidelines?node-id=2%3A4401&viewport=-36%2C134%2C0.37746772170066833&scaling=min-zoom)

**Comment by TheBusyBiscuit** [comment]
Their color theme changes every year, but yeah I would probably stick to their current brand guidelines XD

**Comment by seeseemelk** [comment]
Do you know a good resource for `CONTRIBUTING.md` examples?

**Comment by TheBusyBiscuit** [comment]
I think https://opensource.guide/ is generally a good source of information for best practices around Open-Source development.

One example of a good `CONTRIBUTING.md` file (which GitHub pointed out in their blog post) was the one from puppet:
https://github.com/puppetlabs/puppet/blob/master/CONTRIBUTING.md

But I think it's better to just write your own file and see what should go in there. The file should outline how developers can contribute to this project (e.g. by raising an issue or creating a pull request), what guidelines they should follow (like semantic versions, unit tests or code styles for example) or how new developers could get started working on this, like a quickstart guide.

I reckon that document is probably somewhat unique to every community/project anyway, but feel free to look at the example I linked or other projects' `contributing.md` files.
