### ISSUE TITLE
Implement player movement

### ISSUE THREAD

**Issue by seeseemelk** [MockBukkit/MockBukkit#110]
MockBukkit currently has no way of simulating a player moving around the world, even though many plugins listen to movement related events.

A PR fixing this issue should:
 - Add methods to `PlayerMock` to allow a test script to move the player around.
 - When the player is moving, the right events should be fired.
 - If the event gets cancelled, the player should not move.

Collision detection with the world and with other entities would be nice, but it is not required at this point in time.

**Comment by 0ddlyoko** [comment]
[Baritone](https://github.com/cabaletta/baritone) could be a solution for player movement

**Comment by TheBusyBiscuit** [comment]
This has actually already been implemented via #192 to some degree.



> [Baritone](https://github.com/cabaletta/baritone) could be a solution for player movement
This a mocking framework for the sake of unit-testing, implementing actual movement and navigation logic is far out of scope for this project and not really relevant for the typical use case.
A simple way to write and read the player location with support for the `PlayerMoveEvent` is all that's needed really.
And also all that was outlined in the scope of this issue.

As the aforementioned PR fulfills all these criterias, I will consider this resolved already.
