### ISSUE TITLE
Implement player block placing

### ISSUE THREAD

**Issue by seeseemelk** [MockBukkit/MockBukkit#111]
MockBukkit currently has no way of simulating a player placing a block, although this is a type of action that is performed *a lot* by players.

A PR fixing this issue should:
 - Add a method to `PlayerMock` that allows the player to place a block.
 - When the player is attempting to place a block, an event should be fired.
 - If the event is cancelled, no block should be placed. If the event is not cancelled, a block should be modified in the world.
 
The implementation of this method will likely be similar to the `PlayerMock#simulateBlockBreak(Block)` method.

**Comment by TheBusyBiscuit** [comment]
I think I would like to work on this next, if that's okay with everyone :)

**Comment by seeseemelk** [comment]
Go ahead!

**Comment by bermudalocket** [comment]
Any update on your efforts @TheBusyBiscuit?

**Comment by TheBusyBiscuit** [comment]
I haven't made a pull request for it yet, but I did have the core functionality of this done somewhere in the month of october.
I simply didn't have time to make unit tests for it yet, as other things took priority.

**Comment by bermudalocket** [comment]
> I haven't made a pull request for it yet, but I did have the core functionality of this done somewhere in the month of october.
> I simply didn't have time to make unit tests for it yet, as other things took priority.

@TheBusyBiscuit Awesome! Any chance you could push that to your fork so I could grab it?

**Comment by JacksonChen666** [comment]
I have been just made aware from the comments that @TheBusyBiscuit may have the work done already, but haven't added unit tests. I have completed the PR by myself and can be merged when travis CI finally decides to run the stuff.
