### ISSUE TITLE
Implement `TeamMock#sendMessage(Component)`

### ISSUE THREAD

**Issue by riazufila** [MockBukkit/MockBukkit#1113]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

Send message to the whole Team. I believe this method is from Adventure API and is shaded together with Paper.

**Comment by 4everTheOne** [comment]
Hi @riazufila , thank you for reporting this issue!
I was able to reproduce the bug and the root cause seems to be related with method audiences, because it's not implemented yet. I'll open a PR to fix this issue.
