### ISSUE TITLE
Implement additional inventory mocks

### ISSUE THREAD

**Issue by seeseemelk** [MockBukkit/MockBukkit#113]
We're currently only supporting three inventory types, let's implement the rest!

A PR should add mock implementaties for any of these inventory types (the ones with a check mark have already been implemented):
 - [x] Anvil
 - [x] Barrel
 - [x] Beacon
 - [x] Blast Furnace
 - [x] Brewing
 - [x] Cartography
 - [X] Chest
 - [x] Crafting
 - [x] Creative
 - [x] Dispenser
 - [x] Dropper
 - [x] Enchanting
 - [x] Ender Chest
 - [x] Furnace
 - [x] Grindstone
 - [x] Hopper
 - [x] Lectern
 - [x] Loom
 - [x] Merchant
 - [X] Player
 - [x] Shulker Box
 - [x] Smithing
 - [x] Smoker
 - [x] Stonecutter
 - [x] Workbench

Note that some of these are not creatable (check `org.bukkit.event.inventory.InventoryType`), so `ServerMock#createInventory` should throw an error. Many of the ones that are creatable can most likely be easily implemented using the `SimpleInventoryMock` class.

**Comment by TheBusyBiscuit** [comment]
:eyes: I am working on Dispenser / Dropper mocks!
https://github.com/TheBusyBiscuit/MockBukkit/commit/1d8dc334fdfcd3203a9a8cb06938fcce7b1e148a

**Comment by seeseemelk** [comment]
I increased the scope of it a wee bit because I thought it would maybe be insane to have 23 separate tickets just for inventories. But the issue can be solved by multiple people and multiple PRs.

**Comment by TheBusyBiscuit** [comment]
Ah okay, that's perfect!<br>
*I also updated my comment to emphasize what exact part I am working on*

**Comment by TheBusyBiscuit** [comment]
@seeseemelk The checklist needs to be updated.

**Comment by seeseemelk** [comment]
Which once have been implemented?

**Comment by seeseemelk** [comment]
Ah, it seems to be Barrel, Dispenser, Dropper, and Shulker Box

**Comment by svew** [comment]
@seeseemelk Looks like lectern has been added as well

**Comment by thelooter** [comment]
This is officially done!
