### ISSUE TITLE
Implement reload functionality

### ISSUE THREAD

**Issue by seeseemelk** [MockBukkit/MockBukkit#114]
Reloading a Bukkit server allows admins to enable and disable plugins without having to restart a server. However, some plugins don't play nice with reloads. Being able to test whether your plugin works correctly after a reload would be a great way to be sure that a plugin supports this functionality. Sadly, MockBukkit currently does not support server reload operations.

A PR that fixes this issue should:
 - Implement the `ServerMock#reload()` method.
 - Unload and reload all loaded plugins.
 - Preserve Metadata on entities and blocks.
 - Clear any registered event listeners.
 - Clear any registered timers.

**Comment by Insprill** [comment]
Just a note here related to #360, since we're now building on Paper I'm going to clear entity metadata since [that's what they do](https://github.com/PaperMC/Paper/blob/master/patches/server/0064-Remove-Metadata-on-reload.patch).
