### ISSUE TITLE
Implement the boss bar API

### ISSUE THREAD

**Issue by seeseemelk** [MockBukkit/MockBukkit#115]
Bukkit has APIs to show and control the boss bar. MockBukkit does not yet implement this functionality.

A PR that fixes this issue should:
 - Implement the methods `createBossBar`, `getBossBars`, `getBossBar`, and `removeBossBar` in `ServerMock`.
 - Provide a `BossBarMock` class which implements the `BossBar` interface.

**Comment by ohowe1** [comment]
Is it okay if I take this one?

**Comment by seeseemelk** [comment]
Sure! You can go ahead and add this!

**Comment by ohowe1** [comment]
Created the pull request: #117

**Comment by seeseemelk** [comment]
Merged #117
