### ISSUE TITLE
RegistryMock is not abstract and does not override abstract method getOrThrow(NamespacedKey) in Registry

### ISSUE THREAD

**Issue by Braekpo1nt** [MockBukkit/MockBukkit#1170]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest version of MockBukkit?

- [X] I am using the latest version of MockBukkit.

### Minecraft Version

1.21

### Describe the bug

When attempting to build the [latest version of MockBukkit at the time of writing](https://github.com/MockBukkit/MockBukkit/releases/tag/v3.133.1), I get a build error:
```
RegistryMock.java:42: error: RegistryMock is not abstract and does not override abstract method getOrThrow(NamespacedKey) in Registry
public class RegistryMock<T extends Keyed> implements Registry<T>
       ^
  where T is a type-variable:
    T extends Keyed declared in class RegistryMock
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files additionally use or override a deprecated API that is marked for removal.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error
100 warnings
```
(I'm also getting 100 deprecation warnings, but that's another problem)
Things that were working a few hours ago, stopped working due to this error. 

### Reproducible Test

Simply checkout the latest version of the branch and run the `./gradlew clean build` task to see this happen. 

### Anything else?

I'm not experienced enough with how Bukkit makes releases to know whether this is a Bukkit issue or a MockBukkit issue. Either way, MockBukkit simply isn't overriding the appropriate methods anymore.

**Comment by Thorinwasher** [comment]
This is an issue from mockbukkit: we need to constantly be on par with the paper api, which will change in the same release.

We are currently preparing for a new major release, the patch has already been done in that branch. It might still take some days until this is released (no ETA), I therefore recommend explicitly defining exactly the api version that works with mockbukkit

**Comment by Braekpo1nt** [comment]
@Thorinwasher this makes sense, and it's what I suspected. I need advice though, I can't figure out how to specify an earlier API version. Every tutorial I find just says to use `R0.1-SNAPSHOT`, which downloads the latest one.

**Comment by Thorinwasher** [comment]
There's an extra tag you need to use I don't remember exactly what it is. I recommend going to our discord and asking this if you want a quick response (I will sleep soon)

**Comment by seeseemelk** [comment]
#1171 fixed this
