### ISSUE TITLE
FireworkMetaMock::hasPower not implemented

### ISSUE THREAD

**Issue by ens-gijs** [MockBukkit/MockBukkit#1212]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest version of MockBukkit?

- [X] I am using the latest version of MockBukkit.

### Minecraft Version

1.21

### Describe the bug

FireworkdMetaMock has the following implementation (MockBukkit-1.21-4.7.0)

```java
	@Override
	public boolean hasPower()
	{
		// TODO Auto-generated method stub
		throw new UnimplementedOperationException();
	}
```

### Reproducible Test

```java
    @Test
    public void testRocketHasPower() {
        ItemStack rocket = ItemStack.of(Material.FIREWORK_ROCKET);
        rocket.editMeta(FireworkMeta.class, m -> m.setPower(5));
        assertTrue(((FireworkMeta) rocket.getItemMeta()).hasPower());
    }
```

**Comment by Thorinwasher** [comment]
Seems to have been fixed
