### ISSUE TITLE
Implement Block#breakNaturally functionally

### ISSUE THREAD

**Issue by JacksonChen666** [MockBukkit/MockBukkit#126]
I have a plugin that requires breaking the block (with the plugin) and dropping the drop of the item without triggering the block break event, but it seems to not be implemented, preventing parts of the plugin from being unit tested. I have tried a solution without changing the source code (extended classes), but it took too much effort (of figuring it out), and it still didn't work.

A PR that adds functionality should:

- Simulate a block break without triggering the block break event
- Drop the item that would drop normally from "mining" the block (for Block#breakNaturally, may also require impl of Block#getDrops)

**Comment by JacksonChen666** [comment]
#127 has been closed and should be a linked issue with the PR.

**Comment by seeseemelk** [comment]
Ah, if you write 'fixes #xyz' or 'closes #xyz', this ticket would have been closed automatically. But the PR only says 'This PR linked with issue #126', so it was linked, but wouldn't close automatically.
