### ISSUE TITLE
Implement ItemMocks for in-world items

### ISSUE THREAD

**Issue by seeseemelk** [MockBukkit/MockBukkit#129]
As part of #126, we need `ItemMock`s which implement the `Item` interface. These items should be able to exist in the world at a specific location, and contain a specific item stack.

Once implemented, it would be a step closer to fully correct block breaking and placing.

**Comment by TheBusyBiscuit** [comment]
ehm... :eyes: *cough* *cough*
https://github.com/seeseemelk/MockBukkit/blob/v1.16/src/main/java/be/seeseemelk/mockbukkit/entity/ItemEntityMock.java

**Comment by seeseemelk** [comment]
FSCK! I don't even know more own software anymore :joy:
