### ISSUE TITLE
Support for NMS

### ISSUE THREAD

**Issue by CrushedPixel** [MockBukkit/MockBukkit#139]
We've updated our codebase to MC 1.16.4, but the latest version of MockBukkit doesn't seem to support it:

`java.lang.ClassNotFoundException: net.minecraft.server.v1_16_R3.PacketStatusInListener`

**Comment by yannicklamprecht** [comment]
MockBukkit never had support for NMS only Bukkit/Spigot-API.

**Comment by CrushedPixel** [comment]
Hm, interesting, I was convinced that the same code was testable via MockBukkit before I updated my (rather small) codebase to 1.16.4.

**Comment by seeseemelk** [comment]
It might be possible to add support for NMS, but I doubt that it would be easy given that it is closed source and depends heavily on specific internal things.
The cleanest way to test stuff requiring NMS would be by writing an interface that describes the behaviour you need. You can then write simple class that implements that interface by calling the related NMS methods. You can pass this interface to another class via the constructor. During testing, you provide an alternative implementation of the interface which does not call NMS but rather your own set of functions. This way, the only untested code is the small class which redirects calls to NMS. This class will have to be tested manually, but all other classes can be tested automatically.
Finally, the main plugin method can contain an additional constructor which can be used to pass instances of classes in the test phase. This was created specifically for these kinds of scenarios (altough I see now that this has not yet been documented.)

A small code example on how you would could implement this:
```java
public interface NativeFunctions
{
	void someFunction(int someArg);
}

public class NMSNativeFunctions implements NativeFunctions
{
	@Override
	public void someFunction(int someArg)
	{
		// Perform NMS stuff here
	}
}

public class TestNativeFunctions implements NativeFunctions
{
	private bool called = false;

	@Override
	public void someFunction(int someArg)
	{
		// Validate arguments
		assertEquals(someArg == 5);
		called = true;
	}

	public bool wasCalled()
	{
		return called;
	}
}

public class MyPlugin extends JavaPlugin
{
	private NativeFunctions nativeFunction;

	public TestPlugin()
	{
		super();
		nativeFunctions = new NMSNativeFunctions();
	}

	protected TestPlugin(JavaPluginLoader loader, PluginDescriptionFile description, File dataFolder, File file)
	{
		super(loader, description, dataFolder, file);
		nativeFunctions = new NMSNativeFunctions();
	}
	
	protected TestPlugin(JavaPluginLoader loader, PluginDescriptionFile description, File dataFolder, File file, NativeFunctions nativeFunctions)
	{
		super(loader, description, dataFolder, file);
		this.nativeFunctions = nativeFunctions;
	}

	@Override
	public void onEnable()
	{
		nativeFunctions.someFunction();
	}
}

public class MyPluginTest
{
	private ServerMock server;
	private MyPlugin plugin;
	private TestNativeFunctions nativeFunctions;

	@Before
	public void setUp()
	{
		server = MockBukkit.mock();
		native = new TestNativeFunctions();
		plugin = MockBukkit.load(MyPlugin.class, nativeFunctions);
	}

	// Rest of test class
}
```

**Comment by thelooter** [comment]
Closed since Wont Fix!
