### ISSUE TITLE
Configuration Files

### ISSUE THREAD

**Issue by tatanpoker09** [MockBukkit/MockBukkit#145]
Are config files added by any chance?
If so, which folder does it fetch them from when testing?

Thank you very much beforehand!

**Comment by seeseemelk** [comment]
Yes, when unit tests are ran, the `config.yml` of your current plugin is loaded and can be used during your test.
The `config.yml` file should be in the same directory as the `plugin.yml`, which is most likely located in `src/test/resources`.

**Comment by tatanpoker09** [comment]
Thank you very much! That solves it

**Comment by TheBusyBiscuit** [comment]
I'll close this issue then as it was resolved :)
