### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by 0ddlyoko** [MockBukkit/MockBukkit#157]
This could be good to add more examples (maybe real example or links to other repo that is using this project) so we know how to use this project

**Comment by TheBusyBiscuit** [comment]
Do you have any particular features you want to see?

**Comment by 0ddlyoko** [comment]
Everything

**Comment by JacksonChen666** [comment]
I have a repo using this framework for testing the plugin itself. [Here's just one of the test files.](https://github.com/JacksonChen666/treecapitator/blob/master/src/test/com/jacksonchen666/treecapitator/processings/BreakingBlocksTest.java)
It might not be great or everything, but it works. Hope this helps!

**Comment by TheBusyBiscuit** [comment]
@JacksonChen666 I am currently overhauling the README to address some of the suggestions which were raised in this issue.
Would it be okay for you if I listed your repository there too?

For reference, you can find the current WIP version of the README on my fork here:
https://github.com/TheBusyBiscuit/MockBukkit/blob/improvements/readme/README.md

*(As well as a link to seeseemelk's discord server which is also still WIP)*

On another note: Anyone who enabled notifications and sees this comment, feel free to post yours too if you want me to add it as well.

**Comment by JacksonChen666** [comment]
﻿i'm fine with the idea of listing my repo on the readme. just direct them to either the test folder or just the linked file.
