### ISSUE TITLE
Add example to README (Multiverse Hardcore)

### ISSUE THREAD

**Issue by lluiscamino** [MockBukkit/MockBukkit#196]
Hi,

I'm the developer of a Spigot plugin called [Multiverse Hardcore](https://github.com/lluiscamino/MultiverseHardcore).

I've used MockBukkit to test my plugin, so I thought that maybe it could be added it to the examples section in the README. 😀

**Comment by TheBusyBiscuit** [comment]
Sure 👍🏻 I will add your project shortly, just one thing to note.

I saw that your tests are located in the `src/test/test` directory.
For maven projects, the directory is usually `src/test/java` (in contrast to `src/main/java`), followed by the package. 
See https://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html

The use of the default package is rather discouraged, so just something you may wanna look into.

**Comment by lluiscamino** [comment]
Oops, I didn't know that. I will change the location of the tests then.

Thanks! 😄

**Comment by lluiscamino** [comment]
https://github.com/lluiscamino/MultiverseHardcore/tree/master/src/test/java/me/lluiscamino/multiversehardcore

**Comment by TheBusyBiscuit** [comment]
Added 🚀
