### ISSUE TITLE
Error using sound.getKey().getKey() in AudioExperience

### ISSUE THREAD

**Issue by timkalkus** [MockBukkit/MockBukkit#206]
`mockbukkit/sound/AudioExperience.java` in line 41 `this(sound.getKey().getKey(), category, loc, volume, pitch);` results for me in following error when executed:
`java.lang.NoSuchMethodError: org.bukkit.Sound.getKey()Lorg/bukkit/NamespacedKey;`

Not sure if I have some mistake in my local configuration (because according to the Spigot API `getKey()` should exist) but replacing `sound.getKey().getKey()` with `sound.name()` fixes this issue for me.

**Comment by TheBusyBiscuit** [comment]
Could you perhaps post your `pom.xml` or `build.gradle` file? (Preferabbly via a pasting site like https://pastebin.com)

**Comment by timkalkus** [comment]
[build.gradle](https://pastebin.com/zm6snRPV) for the local mockbukkit instance
[pom.xml](https://pastebin.com/s2QgUq3F) of my plugin
In the IDE itself the method is known, only during runtime the method is not found.

Edit:
[Stacktrace](https://pastebin.com/Lj4BynFU) of the error when executing the tests directly (and not via maven). Interestingly here it is an `ClassNotFoundException` and not a `NoSuchMethodError` as seen in the output from maven.

**Comment by timkalkus** [comment]
Ok, I think I found the error:
I was using the `1.16.1-R0.1-SNAPSHOT` spigot version, changing it to `1.16.5-R0.1-SNAPSHOT` fixed the problem, because in [1.16.1 `Sounds`](https://helpch.at/docs/1.16.1/org/bukkit/Sound.html) didn't yet implement `keyed`

**Comment by TheBusyBiscuit** [comment]
> Ok, I think I found the error:

Alright then! 👍🏻 
Yeah, I suspected something like that, Spigot is an ever-changing api.
