### ISSUE TITLE
Returning the event when something is simulated?

### ISSUE THREAD

**Issue by ohowe1** [MockBukkit/MockBukkit#218]
Hello. I was wondering if it would be useful to others if when a simulate method is called (ie `PlayerMock#simulatePlayerMove`) the event is returned so it could be used in the test to assert that it was cancelled, or action was taken on it, or something else like that. So before I submitted a pull request, I was going to ask if this was something that would align with MockBukkit.

**Comment by wuza8** [comment]
Easy and extends functionality, it should be like that on the first place :+1:

**Comment by TheBusyBiscuit** [comment]
Most simulate methods already return the event or event result.
If `PlayerMock#simulatePlayerMove` doesn't do that, then that must have been an oversight when we reviewed that pull request.
Feel free to submit a pull request for it and we are gonna have a look, makes sense to return the event there.

**Comment by ohowe1** [comment]
> Most simulate methods already return the event or event result.
> If `PlayerMock#simulatePlayerMove` doesn't do that, then that must have been an oversight when we reviewed that pull request.
> Feel free to submit a pull request for it and we are gonna have a look, makes sense to return the event there.

Looking at it now, I am noticing that the block break events return a boolean instead of the event. Should this be fixed? In addition, If it should be replaced by an event should null be returned for when the event is not even fired? (Method would be marked as Nullable of course.)

**Comment by ohowe1** [comment]
One last thing. When running the gradle test task, I don't think that the tests are not actually being run. Is this intentional? I have fixed it on my side with adding this to the build.gradle.
```
test {
    useJUnitPlatform()
}
```

**Comment by ohowe1** [comment]
Closing as pull request has been created.
