### ISSUE TITLE
Removing/Disconnecting player from ServerMock

### ISSUE THREAD

**Issue by wuza8** [MockBukkit/MockBukkit#220]
Is there a way now to disconnect player from ServerMock? I wasn't able to found it so if there's none, what about something like `server.removePlayer(player)`? Name with respect to `server.addPlayer(player)`.

**Comment by wuza8** [comment]
PlayerMock needs ServerMock to instantiate so it would be easy to make methods like `player.connect()` `player.disconnect()` and implement `player.kickPlayer("message")`

**Comment by seeseemelk** [comment]
MockBukkit does not have anything like this yet, but it would definitely be useful to have this!

**Comment by ghost** [comment]
i've already did that in my fork https://github.com/PaTzMC/MockBukkit

**Comment by original-codematrix** [comment]
@tiagodinis33 maybe you can just go ahead and make a new branch and a new PR for e. g. v1.17 where you add that kinda feature for other ppl accessible directly instead of just referring to your fork 🏭

**Comment by Insprill** [comment]
Implemented with #352
