### ISSUE TITLE
Wait for async event execution?

### ISSUE THREAD

**Issue by SpraxDev** [MockBukkit/MockBukkit#251]
Is there a proper way to wait for async events to finish?

I saw that `BukkitSchedulerMock#waitAsyncTasksFinished()` exists, but it doesn't cover async events like `AsyncPlayerChatEvent`.

I am currently trying to test a plugin's reaction on `PlayerMock#chat(String)` and calling `Thread#sleep(long)` isn't optimal in any way.

I am currently using `MockBukkit-v1.16` version `1.5.2`.

**Comment by seeseemelk** [comment]
This is currently lacking. `BukkitSchedulerMock#waitAsyncTasksFinished()` (or another method) should wait on those, but it doesn't at the moment.

**Comment by Silthus** [comment]
I created a PR adding a similar method to the `PluginManager` for waiting on async events.
