### ISSUE TITLE
Better documentation for loading external plugins

### ISSUE THREAD

**Issue by QuakyCZ** [MockBukkit/MockBukkit#252]
Hello,
I'm trying to add 3rd party plugins into unit tests because my plugin depends on them. But I don't know how to do it. In the readme file you say that it's possible.

I have this code:
```java
    @Before
    public void load() throws InvalidPluginException {
        server = MockBukkit.mock();
        
        String externalPlugin = getClass().getClassLoader().getResource("plugins/plugin.jar").getFile();
        MockBukkit.loadJar(externalPlugin);
        plugin = MockBukkit.load(TestPlugin.class);
    }
```

MockBukkit.loadJar(pathToJar) throws this exception.

```log
JavaPlugin requires org.bukkit.plugin.java.PluginClassLoader
```

Could you help me by describing this more detailed please?

**Comment by seeseemelk** [comment]
This is a pretty odd error. Most likely the external plugin does not have the correct constructor, but I might be wrong. Is this code publicly available somewhere so that I can test it out myself?
