### ISSUE TITLE
Suggestion/Discussion: add automatic semantic-release to the pipeline

### ISSUE THREAD

**Issue by Silthus** [MockBukkit/MockBukkit#261]
Hi @seeseemelk,

I wanted to discuss a feature for the ci/cd pipeline: [semantic-release](https://github.com/semantic-release/semantic-release). This workflow action allows for automatic releases and version bumps of the library according to the semantic versioning schema.

It assumes a special commit format ([conventional-commits](https://www.conventionalcommits.org/en/v1.0.0/)) to parse the correct next version and sets it inside the `gradle.properties` and in any other files you want. It will also automatically generate a changelog.

I have this active for all of my projects and since MockBukkit stems on SemVer, I would highly suggest implementing it. This would change the PR checklist from manually bumping the version to automated versioning. But it requires commits to follow the conventional commit format.

You can see the workflow, changelog and versioning in action on all of my projects, e.g.: [spigot-plugin-template](https://github.com/Silthus/spigot-plugin-template). If wanted I will assist and send a PR that implements it in the pipeline.

What do you, and others, think?

**Comment by rona-tombo** [comment]
I think it's very good.

However, in addition to using semantic versioning as a way to increase the versioning, I can think of other ways to add specific labels to the PR (e.x. `version/major`, `version/minor`, `version/patch`, etc.).

**Comment by TheBusyBiscuit** [comment]
I'd love to be able to just label PRs like that and have the version bumped automatically.
If you find an action which does this, feel free to write a workflow and make a pull request @rona-tombo.
I'd happily take a look and consider merging this if seesee agrees (I think he would).

**Comment by seeseemelk** [comment]
I love the idea of being able to bump the version number using a label

**Comment by Insprill** [comment]
Mostly done with #288, leaving open until automatically pushing to Maven Central is implemented.

**Comment by Insprill** [comment]
Fully implemented with #424
