### ISSUE TITLE
MockBukkit#unmock Hangs Indefinitely

### ISSUE THREAD

**Issue by Jikoo** [MockBukkit/MockBukkit#263]
#250 appears to have introduced a bug that causes MockBukkit to hang indefinitely when unmocking. This is largely due to the fact that `PluginManagerMock#disablePlugins` is not called until after the scheduler blocks for shutdown.
https://github.com/MockBukkit/MockBukkit/blob/99821e8e97e2ee54288308a00d6f3cd575ea12c1/src/main/java/be/seeseemelk/mockbukkit/MockBukkit.java#L311-L317
Not only is there no way for the plugin to know it is expected to stop scheduling tasks, sync tasks are not ignored. That means that any sync task in the scheduler will cause an unmock call to block forever.

Manually cancelling tasks prior to unmocking works, but that shouldn't be necessary. I've downgraded MockBukkit-1.17 to 1.10.0 and unmocking works as expected.

**Comment by Luukth** [comment]
Can confirm this is also happening with MockBukkit-v1.16 version 1.5.2

**Comment by Luukth** [comment]
Bumping this as it is still present in MockBukkit-v1.18 version 1.15.0

**Comment by Luukth** [comment]
Adding the following two tests in `src/test/java/be/seeseemelk/mockbukkit/scheduler/BukkitSchedulerMockTest.java` demonstrates the problem. The first test shows an example of a repeating task that will keep on running. The second test shows that when the repeating task is cancelled the scheduler can shutdown succesfully.

```java
@Test
// This will probably crash, run test with care.
void repeatingTask_Keeps_Running_Indefinitely() {
    scheduler.runTaskTimer(null, () -> System.out.println("I ran"), 0, 30);
    
    scheduler.shutdown();
}
```

```java
@Test
void repeatingTask_Stops_Running() {
    BukkitTask task = scheduler.runTaskTimer(null, () -> System.out.println("I ran"), 0, 30);
    scheduler.performTicks(60);
    
    task.cancel();
    
    scheduler.shutdown();
}
```

My guess is that the following lines cause the "hanging" of the unmock().
https://github.com/MockBukkit/MockBukkit/blob/99821e8e97e2ee54288308a00d6f3cd575ea12c1/src/main/java/be/seeseemelk/mockbukkit/scheduler/BukkitSchedulerMock.java#L158-L162

**Comment by deeprobin** [comment]
Fyi: I have the same issue :smile:.

https://github.com/chaos-olymp/portals/actions/runs/1634847340

**Comment by Jikoo** [comment]
This has not been resolved. Here's a simple test that hangs after the changes made by #250:

```java
import be.seeseemelk.mockbukkit.MockBukkit;
import org.bukkit.plugin.Plugin;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInstance;

@TestInstance(TestInstance.Lifecycle.PER_CLASS)
public class SchedulerTest {

  @Test
  void testSchedulerUsage() {
    MockBukkit.mock();
    Plugin plugin = MockBukkit.createMockPlugin("SampleText");
    plugin.getServer().getScheduler().runTaskLater(plugin, () -> {}, 1L);
    MockBukkit.getMock().getScheduler().performTicks(2);
    MockBukkit.unmock();
  }

}
```

This test still causes a hang on `MockBukkit#unmock` using MockBukkit-v1.18 1.24.1.

**Comment by phybros** [comment]
+1 to reopen @Jikoo . Still broken on MockBukkit-v1.16:1.5.2. 1.5.0 works though.

**Comment by Insprill** [comment]
I've just created a new PR to address more hanging issues and backported it to 1.16-1.18. Just waiting for it to be merged. Can you guys see if #532 is still needed afterward?

**Comment by Jikoo** [comment]
Sorry for the late response - appears to work fine for me in a small project now, though I haven't yet updated MockBukkit in the project the majority of my scheduler-based test issues appeared in.
