### ISSUE TITLE
NPE when loading plugin with commands

### ISSUE THREAD

**Issue by ThePhilderbeast** [MockBukkit/MockBukkit#29]
when loading a plugin that has commands that the Executors are in other classess a NPE is thrown

i.e. if you have a line that looks like this:

`this.getCommand("testCommand").setExecutor(new TestCommand());`

edit: this only happens when commands are in the plugin.yml with uppercase characters.

**Comment by tatanpoker09** [comment]
If in a hurry you can just clone my fork and use that instead

**Comment by seeseemelk** [comment]
Did @tatanpoker09's pull request fix this issue?
If not, can you write a small unit test that demonstrates this issue?

**Comment by TheBusyBiscuit** [comment]
Sorry for the necropost but there hasn't been an update on this in over 1.5 years now O_o
Can this be closed or is there still a reason to keep this issue open?
