### ISSUE TITLE
Add Automatic-Module-Name to manifest 

### ISSUE THREAD

**Issue by tim-savage** [MockBukkit/MockBukkit#291]
Using MockBukkit as a dependency in a project that uses Java 9 modules fails, apparently due to an inability to convert the jar name into an automatic module name. Explicitly setting an automatic module name in the jar's manifest would fix this while preserving compatibility with earlier java versions.

See this document for an explanation and instructions to add to the gradle.build file:
http://branchandbound.net/blog/java/2017/12/automatic-module-name/

**Comment by Insprill** [comment]
Do you have an example project you could provide?
