### ISSUE TITLE
InventoryMock.getViewers

### ISSUE THREAD

**Issue by Islati** [MockBukkit/MockBukkit#293]
Not sure why this isn't implemented, but could someone point me in the right direction? It's causing my entire compile to just not happen because of how the logic's designed.

**Comment by thelooter** [comment]
That should in theory be as simple as adding a List with the viewers to the InventoryMock. A Method to add Viewers would be also needed. Shouldn't be too hard to implement

**Comment by Islati** [comment]
<3 This is awesome. Thank you.
