### ISSUE TITLE
No 1.17+ artifacts available

### ISSUE THREAD

**Issue by andret2344** [MockBukkit/MockBukkit#298]
Under [this](https://hub.spigotmc.org/nexus/content/repositories/public/com/github/seeseemelk/) url there are only 1.13-1.16 artifacts, but in the README 1.18 is used.

Screen:
![image](https://user-images.githubusercontent.com/40674613/151264995-3ede15a6-ffd3-4460-86cc-fdc0996d4d97.png)

**Comment by TheBusyBiscuit** [comment]
MockBukkit is NOT hosted on spigotMC's nexus repository.
It is hosted on sonatype/maven-central.

We don't host the link you provided, they are just mirroring some artifacts.
To reference MockBukkit, always consult maven-central, you can find a link in our README:
https://search.maven.org/search?q=MockBukkit

**Comment by andret2344** [comment]
Then in the README https://github.com/MockBukkit/MockBukkit#mag-usage there shouldn't be link to repository to spigot, it's confusing

**Comment by TheBusyBiscuit** [comment]
You will need Spigot for any Spigot plugin.
However in the README it is also clearly stated that MockBukkit can be found on maven-central.
I guess that line can be removed but there has never been any confusion with that until now. Since it should be pretty straight-forward to understand.
