### ISSUE TITLE
Could not find spigot-api-1.18.1-R0.1-SNAPSHOT.jar

### ISSUE THREAD

**Issue by nitkanikita21** [MockBukkit/MockBukkit#301]
Hey! I am trying to include MockBukkit in my gradle project. An error was encountered while importing:
```
Could not find spigot-api-1.18.1-R0.1-SNAPSHOT.jar (org.spigotmc:spigot-api:1.18.1-R0.1-SNAPSHOT:20220130.000032-56).
Searched in the following locations:
    https://hub.spigotmc.org/nexus/content/repositories/snapshots/org/spigotmc/spigot-api/1.18.1-R0.1-SNAPSHOT/spigot-api-1.18.1-R0.1-20220130.000032-56.jar
```
These are my imports:
![image](https://user-images.githubusercontent.com/53836019/153854771-096adaa2-a3fa-455f-b373-75a44dcb6e00.png)

in my project i use paperWeight

**Comment by seeseemelk** [comment]
The Spigot team generally purges any old versions of the spigot-api jar after a month or two. That makes it very difficult for us to depend on a stable version, and can cause the occasional `Could not find spigot-api-<veresion>-SNAPSHOT.jar` error.

There are two things you can try:
 - Simply rerun the import. Spigot's servers have a tendency to throw errors randomly. Not much we can do about that.
 - Update from Mockbukkit `1.15.5` to `1.18.1`. A newer MockBukkit version almost certainly depends on a newer Spigot API snapshot which has (hopefully) not yet been purged.

**Comment by Insprill** [comment]
Closing this as Paper (seems) to keep builds for longer, and there isn't anything we can do about it anyway.
