### ISSUE TITLE
HoverEvent and ClickEvent support

### ISSUE THREAD

**Issue by voidpointer0x00** [MockBukkit/MockBukkit#339]
I ran into a problem: it is impossible to check whether the TextComponent messages are being sent correctly. Currently when you send a `BaseComponent[]` message to a `PlayerMock` it sends plain legacy text, but omits `HoverEvent` and `ClickEvent` within `TextComponent` objects.

https://github.com/MockBukkit/MockBukkit/blob/ca66b487b3c4303f46f9f73fd2223954601db7df/src/main/java/be/seeseemelk/mockbukkit/entity/PlayerMock.java#L2360

I reckon it would be nice to have `BaseComponent[]` messages either in format of JSON or in some other way that you like :)

**Comment by thelooter** [comment]
We switched to Paper so Kyori TextComponents would be the preferred way of doing things. But should we add support for this to have some kind of Backwards Compatibility on this?

**Comment by voidpointer0x00** [comment]
The thing is my plugin sends all messages using [`CommandSender#sendMessage(BaseComponent[])` ](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/command/CommandSender.Spigot.html#sendMessage(net.md_5.bungee.api.chat.BaseComponent)) method, so there's just no way to test if it does it the way it's intended or if some commands give the expected output or not. I don't want to use Paper's API, because even though 60% servers run Paper, the plugin won't run on other 40%.

It's not hard to add after all :)

**Comment by thelooter** [comment]
Thats a valid point. We will look into it. Just for clarification. What version of Mockbukkit are you running?

**Comment by Insprill** [comment]
With #412, BungeeCord Components will be internally converted to Adventure Components and an assert method will be added accordingly.

**Comment by voidpointer0x00** [comment]
@thelooter, I'm using 1.24.1
@Insprill thanks, much appreciated :)
