### ISSUE TITLE
Class file has wrong version 61.0, should be 52.0

### ISSUE THREAD

**Issue by matsgemmeke** [MockBukkit/MockBukkit#346]
When using this library in my tests I get this error message:

`java: cannot access be.seeseemelk.mockbukkit.MockBukkit
  bad class file: /C:/Users/Mats/.m2/repository/com/github/seeseemelk/MockBukkit-v1.18/1.24.1/MockBukkit-v1.18-1.24.1.jar!/be/seeseemelk/mockbukkit/MockBukkit.class
    class file has wrong version 61.0, should be 52.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.`

It appears that the maven artifact was compiled with Java 17, and therefore I can't use it in my Java 8 project.

**Comment by TheBusyBiscuit** [comment]
Yes that is correct.
You will need Java 17 to be able to access classes that were compiled with Java 17.
Please update your Java version, you are quite far behind.

By the way Java is backwards-compatible. So you can still compile against Java 8, even if you have newer versions installed.
