### ISSUE TITLE
Consider switching from CodeClimate to Sonarcloud

### ISSUE THREAD

**Issue by thelooter** [MockBukkit/MockBukkit#353]
Since it seems like CodeClimate was abandoned after 1.15 I suggest switching to Sonarcloud

**Comment by TheBusyBiscuit** [comment]
+1 for Sonarcloud, I am using it for most of my projects since years too

**Comment by thelooter** [comment]
I have Sonarqube setup for my Personal Projects, but I think Sonarqube would be a better fit for this
