### ISSUE TITLE
Recognize all Contributors

### ISSUE THREAD

**Issue by thelooter** [MockBukkit/MockBukkit#499]
We should Recognize all Contributors as layed out by the https://allcontributors.org/ Standart.
This would add a Panel to the README.md which recognizes all Contributors

**Comment by thelooter** [comment]
Any Input on this?

**Comment by Insprill** [comment]
I'm down for it.

**Comment by Insprill** [comment]
@seeseemelk @TheBusyBiscuit What are your thoughts?

**Comment by seeseemelk** [comment]
The idea looks good, that bot does not.
Why should we assume that all contributors have GitHub accounts?

**Comment by thelooter** [comment]
Whats your suggestion instead

**Comment by Insprill** [comment]
I think for now the GitHub Contributors list is good enough. Once we have more people actively making large contributions, we can revisit this.
