### ISSUE TITLE
PlayerMock#assertSaid not working correctly with BungeeCord Components

### ISSUE THREAD

**Issue by PeachesMLG** [MockBukkit/MockBukkit#550]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest version of MockBukkit?

- [X] I am using the latest version of MockBukkit.

### Minecraft Version

1.19

### Describe the bug

Looks like my component isnt being asserted correctly, looks like its messing up due to the colour or something.

### Reproducible Test

```java
    @Test
    public void test(){
        PlayerMock playerMock = serverMock.addPlayer();
        TextComponent previousButton = new TextComponent(ChatColor.translateAlternateColorCodes('&', "&c<<"));
        playerMock.spigot().sendMessage(previousButton);
        playerMock.assertSaid(ChatColor.translateAlternateColorCodes('&',"&c<<"));
    }
```

### Anything else?

Side note, since the update we are serialising messages into json chat components which makes failing tests alot harder to debug, would be cool if we could find a way to make it easier to see the differences
![image](https://user-images.githubusercontent.com/26843204/179371441-27e92cf2-b638-4475-9329-acdbe77bd455.png)

**Comment by Thorinwasher** [comment]
Serialize to minimessage first before printing?

**Comment by 4everTheOne** [comment]
Hi @PeachesMLG could you please validate if https://github.com/MockBukkit/MockBukkit/pull/1082 fixed the issue?
Thanks in advance.

**Comment by 4everTheOne** [comment]
I'll mark this issue as resolved. If someone identifies that it was not resolved yet we can re-open it
