### ISSUE TITLE
The JavaPlugin#getPlugin methods fail tests

### ISSUE THREAD

**Issue by NeumimTo** [MockBukkit/MockBukkit#582]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest version of MockBukkit?

- [X] I am using the latest version of MockBukkit.

### Minecraft Version

1.18

### Describe the bug

My plugin utilizes https://github.com/stefvanschie/IF and this framework relies on `JavaPlugin#getProvidingPlugin`.

https://github.com/stefvanschie/IF/blob/master/IF/src/main/java/com/github/stefvanschie/inventoryframework/gui/GuiItem.java#L31

```java
    @NotNull
    public static JavaPlugin getProvidingPlugin(@NotNull Class<?> clazz) {
        Validate.notNull(clazz, "Null class cannot have a plugin");
        final ClassLoader cl = clazz.getClassLoader();
        if (!(cl instanceof PluginClassLoader)) {
            throw new IllegalArgumentException(clazz + " is not provided by " + PluginClassLoader.class);
        }
        JavaPlugin plugin = ((PluginClassLoader) cl).plugin;
        if (plugin == null) {
            throw new IllegalStateException("Cannot get plugin for " + clazz + " from a static initializer");
        }
        return plugin;
    }
```
    
This method, and `JavaPlugin#getPlugin` throw exceptions as the classloader is type of `jdk.internal.loader.ClassLoaders.AppClassLoader`.

### Reproducible Test

```java
public class MockTest {
    @Test
    public void test() {
        MockBukkit.mock();
        MockPlugin test = MockBukkit.createMockPlugin("test");

        JavaPlugin.getProvidingPlugin(MockTest.class);
    }
}
```

**Comment by Insprill** [comment]
Closing so it can be tracked in #642
