### ISSUE TITLE
ItemMeta Serialization Methods

### ISSUE THREAD

**Issue by EbonJaeger** [MockBukkit/MockBukkit#59]
Currently, the ItemMeta serialization (and I presume deserialization) methods are not implemented. My use case is serializing and deserializing inventory items and using tests to make sure that happens as expected. This involves ItemMeta, and I really don't want to maintain my own implementation.

If I find the time, I can probably implement this myself and PR it, but in case someone else wants to get to it before me, I'll just leave this issue here. :)

**Comment by seeseemelk** [comment]
Hm, I don't think this should be all that hard. If I remember correctly, `ItemMetaMock` should not be depending on any other entities, so serialisation should be fairly plain and simple.

**Comment by maxphillipsdev** [comment]
Working on implementing this now on a fork, got the serialize method done and tested, just need to deserialize and register it now. 🙂
EDIT: [Link to the commit](https://github.com/blueybloke/MockBukkit/commit/78438d4ba861bfef66950cf4408ce7531da0495d) if anyone wants to check it out, I'm still a bit new to OSS contribution so feedback is welcome
