### ISSUE TITLE
get for player mainHeldItem result discrepant

### ISSUE THREAD

**Issue by CuteLuoBo** [MockBukkit/MockBukkit#616]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest version of MockBukkit?

- [X] I am using the latest version of MockBukkit.

### Minecraft Version

1.18

### Describe the bug

Hello, I am a developer from China, my English is not good, I used google translation, please forgive me

usage version:
spigot-api:1.18.2-R0.1-SNAPSHOT
paper-api:1.18.2-R0.1-SNAPSHOT
MockBukkit-v1.18:2.26.0

I'm testing operations related to player inventory, but I'm using MockBukkit generated Player object and testing methods to spawn items in the second hotbar slot of the player:
```
Player player = playerMock.getPlayer();
player .getInventory().setItem(1, appointItem);
```
and use
 ```
player.getInventory().setHeldItemSlot(1);
server.getPluginManager().callEvent(new PlayerItemHeldEvent(player, 0, 1));
```
 to toggle player hotbar (0->1)
 and When getting the main hand item
```
int heldItemSlot = player.getInventory().getHeldItemSlot();
ItemStack heldItem = player.getInventory().getItem(heldItemSlot);//ok=STONEx1
ItemStack holdItem = player.getInventory().getItemInMainHand();//error=AIR
```
it should normally return STONEx1, but it is found that the test has not passed the test after many adjustments (returns AIR). 
![image](https://user-images.githubusercontent.com/44561136/187024124-3f319d7b-a6dc-40aa-acb3-0b36d72df002.png)
However, items can be obtained normally in the server.
![image](https://user-images.githubusercontent.com/44561136/187024266-a7862da3-7e71-4d05-97bc-13e5042b66a0.png)
![image](https://user-images.githubusercontent.com/44561136/187024291-98ba6367-3688-4962-a461-42df08288869.png)

After observing the source code, I found that SLOT_BAR was added to the corresponding method to point to the main hand item slot. Under normal circumstances, the player's second shortcut slot index is 1, but the index in PlayerMock is 10
![image](https://user-images.githubusercontent.com/44561136/187025061-6eabc72a-b367-4213-8320-f423cb122191.png)

Although this can be achieved with code like this plan.B:
```
player.getInventory().setHeldItemSlot(testHeldItemSlot);
player.getInventory().getItemInMainHand()
```
, when the PlayerItemHeldEvent in the original version passes the switched slot index (0->1), it will cause the item to not be obtained correctly

### Reproducible Test

##test
```
public class BugTest {

    private static ServerMock server;
    private static TestPlugin plugin;

    @BeforeAll
    public static void setUp() {
        server = MockBukkit.mock();
        plugin = MockBukkit.load(TestPlugin.class);
    }

    @AfterAll
    public static void tearDown() {
        MockBukkit.unmock();
    }

    @Test
    public void test() {
        PlayerMock playerMock = server.addPlayer();
        Player player = playerMock.getPlayer();
        assert player != null;

        ItemStack item = new ItemStack(Material.STONE);
        int testHeldItemSlot = 1;
        int airHeldItemSlot = 0;

        player.getInventory().setHeldItemSlot(testHeldItemSlot);
        player.getInventory().setItemInMainHand(item);

        server.getPluginManager().callEvent(new PlayerItemHeldEvent(player, airHeldItemSlot, testHeldItemSlot));
    }
}
```
##TestEventListener
```
public class TestEventListener  implements Listener {
    @EventHandler
    public void eventHandler(PlayerItemHeldEvent playerItemHeldEvent) {
        Player player = playerItemHeldEvent.getPlayer();
        ItemStack newHeld = player.getInventory().getItem(playerItemHeldEvent.getNewSlot());
        ItemStack oldHeld = player.getInventory().getItem(playerItemHeldEvent.getPreviousSlot());
        assert (newHeld) !=null;
        assert (oldHeld) !=null;
        assert newHeld.getType() == Material.STONE;
        assert oldHeld.getType() == Material.AIR;
    }
}
```
##TestPlugin
```
public class TestPlugin extends JavaPlugin {
    public TestPlugin()
    {
        super();
    }

    protected TestPlugin(JavaPluginLoader loader, PluginDescriptionFile description, File dataFolder, File file)
    {
        super(loader, description, dataFolder, file);
        Class<BetterWorld> betterWorldClass = BetterWorld.class;
    }

    @Override
    public void onEnable() {
        Bukkit.getPluginManager().registerEvents(new TestEventListener(), this);
    }
}
```

**Comment by thelooter** [comment]
Can you check if the Bug still exists in the newest version of the 1.19 Branch? There have been some changes to some of this stuff. If it's fixed we should be able to just backport it to 1.18

**Comment by CuteLuoBo** [comment]
> 能检查下最新版本的 1.19 分支中是否还存在这个 Bug 吗？其中一些内容发生了一些变化。如果它已修复，我们应该能够将其反向移植到 1.18

Looks like it has the same problem
- usage version:
spigot-api:1.19.2-R0.1-SNAPSHOT
paper-api:1.19.2-R0.1-SNAPSHOT
com.github.seeseemelk:MockBukkit-v1.19:2.29.0


![image](https://user-images.githubusercontent.com/44561136/187368968-46c1f3f0-1b76-4c52-b4b8-6c81311ec8e4.png)

- usage version:
paper-api:1.19.2-R0.1-SNAPSHOT
com.github.MockBukkit:MockBukkit:v2.117.1
![image](https://user-images.githubusercontent.com/44561136/187430332-b3cfb6c9-55ea-4b5f-a013-40df1f08a49d.png)
