### ISSUE TITLE
MockBukkit#unmock() does not unload plugin classes

### ISSUE THREAD

**Issue by Vadim998082** [MockBukkit/MockBukkit#617]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest version of MockBukkit?

- [X] I am using the latest version of MockBukkit.

### Minecraft Version

1.18

### Describe the bug

I had some child threads in my plugin, and one of them is singleton:
![изображение](https://user-images.githubusercontent.com/45773532/187913727-225b4224-36a0-444a-8c71-fcf80c4b7071.png)
![изображение](https://user-images.githubusercontent.com/45773532/187913968-9581ed6e-69a6-49bf-81f5-2f53cfbe7ce4.png)
this thread is starting in onEnable()
I had two tests running in one scope:
![изображение](https://user-images.githubusercontent.com/45773532/187914093-2f83434b-d09f-42db-be56-575a8255e7a7.png)
As you see, one test is successfull and one is with error. But the error hints that plugin is not completely shutdown:
![изображение](https://user-images.githubusercontent.com/45773532/187914473-76b713fe-5659-406f-bbf4-d074d2b3ccb0.png)
I added some logs to see the state of the singleton thread before calling #start() and i saw that in the second test it was already WAITING, but it is terminal state that appeared after interrupting. Also one test class uses @AfterAll and the other - @AfterEach. During invesigation i came to conclusion that it does not affect on resulsts of tests, it affects only what test will fail with such error. My singleton config storages also had problems because of that, in onDisable() method i do not do clearing configs, and after calling second test with booting server and plugin, i had duplicated configs in storages. I think there is a problem with shutdown incmoplition of server/plugin when unmock() is called.

### Reproducible Test

1. in empty plugin make singleton thread extended from Thread or Runnable
2. call start of child thread in onEnable()
3. call interrupt of child thread in onDisable()
4. wright 2 test classes so that they have one test each and use @BeforeAll and @AfterAll in both OR wright 2 tests in one class and use @BeforeEach and @AfterEach
5. in @Before call startup of test server and plugin
6. in @After call .unmock()
7. Run both tests in one scope
8. Second runned test will fail with illegal state of thread

**Comment by Vadim998082** [comment]
As WA i removed singleton pattern from the thread and do cleaning up configs in onDisable()

**Comment by Insprill** [comment]
Closing so it can be tracked in #642
