### ISSUE TITLE
Allow loading plugins with the PluginClassLoader

### ISSUE THREAD

**Issue by Insprill** [MockBukkit/MockBukkit#642]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

When loading plugins, ideally we'd be able to load the classes using the PluginClassLoader. This would fix #582 and #617.

**Comment by Travja** [comment]
I just want to note here, I was playing around with this today and was able to get things sort of working. I've got some NMS/reflection stuff going on in my dependency that I need to sort out so I'm not throwing ClassNotFounds all over the place. Once (if?) I am able to get things rolling properly here, I can see about creating a pull request.

**Comment by Travja** [comment]
I regret to inform you that through all my best efforts.... I could get plugins to load up properly with applicable PluginClassLoaders but for some reason couldn't get them to all be loaded in the same context. Thus, secondary plugins would generate their files and load up as one would expect, but would not be accessible in the same context as the original mocked plugin. If they were accessible, the trade-off would be a lack of scoped plugin resources. I'm not entirely sure why it behaves the way it does or how to get it to behave properly.

My efforts all feel a bit scattered and not all-too-effective, but I can elaborate more on what I've tried if it interests you.

**Comment by thelooter** [comment]
More information on your approaches would be greatly appreciated. Our current effors can be found under 819ab18064f5cb7d5e2f39a60df47a22f8b508e4

**Comment by Insprill** [comment]
Closing since the entire plugin loading system has changed with the introduction of Paper plugins.
