### ISSUE TITLE
ItemStack.getData throws UnimplementedOperationException

### ISSUE THREAD

**Issue by ChristopherHaws** [MockBukkit/MockBukkit#666]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest version of MockBukkit?

- [X] I am using the latest version of MockBukkit.

### Minecraft Version

1.19

### Describe the bug

`ItemStack.getData` calls `MockUnsafeValues.toLegacy` which throws an `UnimplementedOperationException` if the material is not a legacy material.

My plugin calls `getData` because, as far as I know, it is the only way to get the type of potion or book from an `ItemStack`.

### Reproducible Test

```java
new ItemStack(Material.POTION, 1).getData();
```

**Comment by Insprill** [comment]
Same root cause as #300.
