### ISSUE TITLE
Disconnect doesn't call PlayerQuitEvent if PlayerMock is constructed with ServerMock#addPlayer(String)

### ISSUE THREAD

**Issue by Travja** [MockBukkit/MockBukkit#691]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest version of MockBukkit?

- [X] I am using the latest version of MockBukkit.

### Minecraft Version

1.19

### Describe the bug

Disconnect doesn't appear to be calling PlayerQuitEvent if the PlayerMock is built using only a name and not a UUID. If a player is created with just a name, no UUID, the `online` field in the PlayerMock is set to false, even though `isOnline()` will return true because they're in the online player list. `disconnect()` uses that `online` field to determine if the event should fire but it is `false`, so the event doesn't fire.

If I create the player with new and with a UUID, the disconnect method works as I would assume it should but with just the ServerMock#addPlayer it does not.

### Reproducible Test

```java
    @Test
    public void quitNoWork() {
        PlayerMock travja = server.addPlayer("Travja");
//        Comment ^ and uncomment below and it works
//        PlayerMock travja = new PlayerMock(server, "Travja", UUID.randomUUID());
//        server.addPlayer(travja);
        travja.disconnect();
        server.getPluginManager().assertEventFired(PlayerQuitEvent.class, e -> {
            System.out.println("Event was fired!");
            return true;
        });
    }
```

### Anything else?

[PlayerMock:164](https://github.com/MockBukkit/MockBukkit/blob/v1.19/src/main/java/be/seeseemelk/mockbukkit/entity/PlayerMock.java#L164) indicates the player should be considered offline, but this field is not updated when `ServerMock#addPlayer` is called.

**Comment by NullTxt** [comment]
Found exact line I believe https://github.com/MockBukkit/MockBukkit/blob/34ae8cf1350274044c27550144942afa8bb5b222/src/main/java/be/seeseemelk/mockbukkit/entity/PlayerMock.java#L182
