### ISSUE TITLE
Jitpack build failure

### ISSUE THREAD

**Issue by LinoxGH** [MockBukkit/MockBukkit#81]
https://jitpack.io/com/github/seeseemelk/MockBukkit/v1.15-1958733896-1/build.log

Jitpack seems to be unable to build this project because of publishing publications.
I tried to fix this in 2 prs but can't seem to get the handle of it. Please someone with better gradle knowledge than me fix this.

**Comment by seeseemelk** [comment]
I'm working on getting Travis CI to automatically publish new snapshots versions when pull requests are accepted, so hopefully Jitpack won't be needed then anymore.

**Comment by seeseemelk** [comment]
You should be able to get the latest snapshot version straight from maven central now. If this still doesn't work, feel free to reopen this issue!
