### ISSUE TITLE
Cxeb68d52e-5509: Vulnerable issue in commons-codec

### ISSUE THREAD

**Issue by ChrissW-R1** [MockBukkit/MockBukkit#833]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest version of MockBukkit?

- [X] I am using the latest version of MockBukkit.

### Minecraft Version

1.19

### Describe the bug

Info: I'm using MC 1.20, but this is not available in the list! (Maybe 1.2 is a typo?)

The version 1.7.3 of dependency org.apache.maven.resolver:maven-resolver-transport-http has an security issue, because it uses an old version of commons-codec. In version 1.9.15 the issue is fixed.

Please check https://devhub.checkmarx.com/cve-details/Cxeb68d52e-5509/

### Reproducible Test

No test, issue in dependency. See description for more information.

**Comment by Insprill** [comment]
This is an upstream issue. We can't bump it without possibly breaking compatibility. Please raise this issue with the Spigot or Paper team instead.
