### ISSUE TITLE
Remove use of Deprecated Constructor

### ISSUE THREAD

**Issue by thelooter** [MockBukkit/MockBukkit#900]
https://github.com/MockBukkit/MockBukkit/blob/2e865fa5c78782af64763d2dc3763b2b65f49dbb/src/main/java/be/seeseemelk/mockbukkit/entity/PlayerMock.java#L362

The used Constructor for `BlockDamageEvent`is annotated as Deprecated for Removal and and DoNotUse. Therefore we should replace this Constructor

**Comment by JonnyMc94** [comment]
Hi, I would like to work on this issue. Could you assign it to me?

**Comment by thelooter** [comment]
Sure, done

**Comment by JonnyMc94** [comment]
@thelooter I can't seem to find a depreciation marker or a discussion about possible deprecation of this constructor anywhere. Could you point me in the direction of some info on it? 

This file only has one constructor 
https://github.com/Bukkit/Bukkit/blob/master/src/main/java/org/bukkit/event/block/BlockDamageEvent.java

**Comment by thelooter** [comment]
We're building on Paper, not Bukkit (which has been unmaintained since 2014), and they have deprecated this constructor as you can see [here](https://github.com/PaperMC/Paper/blob/f186318a91cbd3b2a2259d39cb88576989a496b8/patches/api/0429-Expose-clicked-BlockFace-during-BlockDamageEvent.patch#L17-L22). Therefore we wanna remove this usage
