### ISSUE TITLE
Upgrade to 1.16?

### ISSUE THREAD

**Issue by stevefan1999-personal** [MockBukkit/MockBukkit#93]

**Comment by seeseemelk** [comment]
I'm looking into this, but it seems that currently the Bukkit API is not yet available for 1.16.2. Interestingly, the Spigot API *is* available.

**Comment by TheBusyBiscuit** [comment]
@seeseemelk Spigot has stopped distributing Bukkit since 1.16, that's why. It will be all-Spigot from here on out.

You can read about it here:
https://www.spigotmc.org/threads/spigot-bungeecord-1-16-1.447405/#post-3852349

**Comment by seeseemelk** [comment]
Ah, I'm actually quite happy about that. No more `*-spigot` versions to maintain. Makes everything a bit simpler for me.

I'm also gonna quickly note here that from now on I'm no longer going to publish snapshot versions of MockBukkit. I'll do a proper release after each PR instead.

**Comment by seeseemelk** [comment]
`MockBukkit-v1.16` should now be on Maven central.

**Comment by TheBusyBiscuit** [comment]
You can pretty much name this `MockSpigot` at this point XD
