### ISSUE TITLE
Cannot publishToMavenLocal on feat/1.20.4

### ISSUE THREAD

**Issue by andrewkm** [MockBukkit/MockBukkit#939]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest version of MockBukkit?

- [X] I am using the latest version of MockBukkit.

### Minecraft Version

1.20

### Describe the bug

When using just `clean build` all is well: https://pastebin.com/raw/DSJtCDLP
But when adding `clean build publishToMavenLocal` it is unsuccessful: https://pastebin.com/raw/T8idDXtd

### Reproducible Test

Use clean build publishToMavenLocal on feat/1.20.4

### Anything else?

Version issue in build.gradle.kts

**Comment by andrewkm** [comment]
Having the same issue on v1.20 after the feat/1.20.4 merge.
https://pastebin.com/raw/pNnzBiLd
@thelooter

**Comment by thelooter** [comment]
I cannot reproduce this locally. Is this maybe related to being build on Jenkins?

**Comment by andrewkm** [comment]
Maybe @electronicboy can elaborate what's happening here.

**Comment by Insprill** [comment]
Please don't ping Paper devs, they're busy enough as-is and this doesn't relate to them.

I also wasn't able to reproduce this so it's most likely a Jenkins issue. Is there a particular reason you're building MockBukkit with Jenkins instead of using the Maven Central builds?

**Comment by andrewkm** [comment]
> Please don't ping Paper devs, they're busy enough as-is and this doesn't relate to them.
> 
> I also wasn't able to reproduce this so it's most likely a Jenkins issue. Is there a particular reason you're building MockBukkit with Jenkins instead of using the Maven Central builds?

Shane works for us.

I'll wait on his response here.
He's the one dealing with this issue for me @Insprill, I merely made the report. He will know more about the problem and will investigate soon.

I believe we were building on Jenkins because we needed the 1.20.4 version for some tests and it wasn’t on maven prior to the merge so attempted to publishtolocal the feat/1.20.4 branch. For some reason still can’t publish that way though.

**Comment by electronicboy** [comment]
https://github.com/MockBukkit/MockBukkit/blob/v1.20/build.gradle.kts#L178

~~What I'd guess here is a "jenkins doesn't define a CI env variable, and so it defers to the system property which is not set", thus, version gets set to null and boom~~

Okay, I got that backwards, Jenkins apparently does define a CI environment variable, however, in doing so, that seems to make it defer to the system property which is not set, and thus blows up

**Comment by Insprill** [comment]
Would checking if the `BUILD_ID` env var exists in `#isAction` solve this? I'm not too familiar with Jenkins, but at a glance, it looks like that's all that needs to be done.

**Comment by thelooter** [comment]
> Would checking if the `BUILD_ID` env var exists in `#isAction` solve this? I'm not too familiar with Jenkins, but at a glance, it looks like that's all that needs to be done.

It might make more sense to check if the property is not set, and if thats the case fall back to the non-action version. Just checking the `BUILD_ID` environment variable might work for Jenkins, but will most likely break on other CI Systems. A fallback guarantees that this won't happen.

**Comment by electronicboy** [comment]
No, because I think that the issue here is that jenkins defines a CI env variable just as actions does, I think that the issue is that it's only intended that the publish task is ran when ran under CI is for a release within your controlled environment,

https://github.com/MockBukkit/MockBukkit/blob/v1.20/.github/workflows/publish.yml#L63

but, that "controlled environment" check overlaps with anybody elses Ci environment, and so the best route here is going to likely be to just check if the property exists

**Comment by andrewkm** [comment]
@Insprill @thelooter 
Are there any plans on a fix for this?

**Comment by Insprill** [comment]
Apologies, this slipped under the radar. I just read through this again and created https://github.com/MockBukkit/MockBukkit/pull/1004 which should solve your problem. Can you confirm?

**Comment by andrewkm** [comment]
Can confirm this has fixed our issue.
Thank you very much!
