### ISSUE TITLE
Compilation: TNTPrimedMock Missing getBlockData Implementation

### ISSUE THREAD

**Issue by andrewkm** [MockBukkit/MockBukkit#949]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest version of MockBukkit?

- [X] I am using the latest version of MockBukkit.

### Minecraft Version

1.20

### Describe the bug

Cannot compile v1.20:
https://pastebin.com/raw/whT9J0Bu

### Reproducible Test

Compile.

### Anything else?
```
/var/lib/jenkins/workspace/MockBukkit/src/main/java/be/seeseemelk/mockbukkit/entity/TNTPrimedMock.java:19: error: TNTPrimedMock is not abstract and does not override abstract method getBlockData() in TNTPrimed
public class TNTPrimedMock extends EntityMock implements TNTPrimed
       ^
```

**Comment by thelooter** [comment]
Done in #950

**Comment by andrewkm** [comment]
@thelooter #950 hasn't fixed it for us.
https://pastebin.com/raw/DATs1gCS

Getting the above when compiling 4.0
