### ISSUE TITLE
Enchantment.values() returns an empty array when testing

### ISSUE THREAD

**Issue by Josse3** [MockBukkit/MockBukkit#95]
When testing, `Enchantment.values()` returns an empty array instead of an array containing all the enchantments.
```java
@Test 
public void sampleTest() {
  final Enchantment[] enchantments = Enchantment.values();
  System.out.println(enchantments); // outputs "[]"

  assertTrue(enchantments.length > 0); // will fail
}
```
<s>Aditionally:
```java
@Test
public void sampleTest() {
  final Enchantment[] enchantments = Enchantment.class.getEnumConstants(); // Will be null
  assertNotNull(enchantments); // will fail
}
```
The fact that `null` is returned from `getEnumConstants()` signifies that `Enchantment` is not considered as an enum at runtime.</s> (Edit: Apparently it is not supposed to be an enum, this is completely my bad)

Edit: It also seems that trying to do anything with an enchantment variable seems to cause a `NullPointerException`, however the values themselves are not null, weird.
```java
@Test
public void sampleTest() {
  System.out.println(Enchantment.SILK_TOUCH); // Will generate NullPointerException
  assertNotNull(Enchantment.SILK_TOUCH); // Will however pass
}
```

**Comment by TheBusyBiscuit** [comment]
> The fact that null is returned from getEnumConstants() signifies that Enchantment is not considered as an enum at runtime.

Enchantment is not an enum, that's completely normal.
It's an abstract class provided by the Bukkit API, the constants are just `public static final` fields in that class.
But yeah, it is not an Enum, so getEnumConstants() being null would be absolutely correct.

However, values() returning an empty array is definitely something that should be fixed.

**Comment by Josse3** [comment]
Ah, interesting, but its `values()` method returning an empty array is not intended behaviour, right?

**Comment by TheBusyBiscuit** [comment]
It should return an array with the Enchantments, yes.
So that is definitely an issue and not intended.
