### ISSUE TITLE
Add Block#getLightFromSky and Block#getLightFromBlocks

### ISSUE THREAD

**Issue by boooiil** [MockBukkit/MockBukkit#953]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

Create an implementation for BlockMock#getLightFromSky and BlockMock#getLightFromBlocks

**Comment by Thorinwasher** [comment]
Just wondering. How exactly should this be implemented? Should there be a script that figures out light levels based on block configurations in the world, or is there an alternative simpler solution for this?

If we're going with a full script that does this, then there are loads of special blocks with specific light behavior, which would need to be implemented.

**Comment by Insprill** [comment]
I think we should simply add setter methods for it. There's no way we can maintain an entire lighting engine that's 1:1 with vanilla/paper, and anything less than that would deviate from expected behaviour

**Comment by Thorinwasher** [comment]
I agree. That would definitely be a lot to maintain.

**Comment by Thorinwasher** [comment]
Fixed with #970
